#!/usr/bin/env python3
"""Generate EduTools answer placeholders from a marked-up solution template.

Authoring model (see CLAUDE.md A8, "Option A"):

  * You write the FULL, correct, runnable solution in a template file named
    ``<realname>.tmpl`` (for example ``main.py.tmpl``).
  * Inside it, you wrap each span the learner must type with a marker:

        [[PH:hint shown in the blank]]the real answer text[[/PH]]

  * This tool strips the markers to produce the clean solution file
    (``main.py``) — which is a real, runnable program — and computes the
    character offset and length of each answer span, writing them into
    ``task-info.yaml`` as EduTools placeholders.

Why a script: offsets are character positions into the solution file, so any
edit shifts them. Re-running this tool after editing the template regenerates
them exactly, instead of counting by hand (CLAUDE.md A8).

The tool is part of the authoring toolchain, so it runs on the system Python
(3.9+). It writes plain-text YAML (no third-party dependency).

The exact EduTools placeholder schema (the field names below) is from background
knowledge of the plugin, not a reference document — confirm the rendered blanks
in the IDE (CLAUDE.md A2, A8).

Usage:
    python tools/build_placeholders.py <task_dir> [<task_dir> ...]
    python tools/build_placeholders.py --all          # every *.tmpl under the repo
    python tools/build_placeholders.py <task_dir> --check   # verify only, write nothing
"""

from __future__ import annotations

import argparse
import glob
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

OPEN = "[[PH:"
HINT_END = "]]"
CLOSE = "[[/PH]]"


def parse_template(text):
    """Return (clean_text, placeholders) from marker-annotated template text.

    Offsets are computed against the *clean* text as it is built, so duplicate
    answer spans and marker-induced shifts are handled correctly.
    """
    clean_parts = []
    placeholders = []
    clean_len = 0
    i = 0
    n = len(text)
    while i < n:
        start = text.find(OPEN, i)
        if start == -1:
            seg = text[i:]
            clean_parts.append(seg)
            clean_len += len(seg)
            break
        # text before the marker passes through unchanged
        seg = text[i:start]
        clean_parts.append(seg)
        clean_len += len(seg)
        hint_end = text.find(HINT_END, start + len(OPEN))
        if hint_end == -1:
            raise ValueError("unterminated hint in marker near offset %d" % start)
        hint = text[start + len(OPEN):hint_end]
        ans_start = hint_end + len(HINT_END)
        close = text.find(CLOSE, ans_start)
        if close == -1:
            raise ValueError("missing %s after marker near offset %d" % (CLOSE, start))
        answer = text[ans_start:close]
        placeholders.append({
            "offset": clean_len,
            "length": len(answer),
            "placeholder_text": hint,
        })
        clean_parts.append(answer)
        clean_len += len(answer)
        i = close + len(CLOSE)
    return "".join(clean_parts), placeholders


def yaml_quote(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def build_task_info(file_entries, has_tests):
    lines = ["# Auto-generated by tools/build_placeholders.py — edit the .tmpl, not this file.",
             "type: edu",
             "files:"]
    for name, placeholders in file_entries:
        lines.append("  - name: %s" % name)
        lines.append("    visible: true")
        if placeholders:
            lines.append("    placeholders:")
            for p in placeholders:
                lines.append("      - offset: %d" % p["offset"])
                lines.append("        length: %d" % p["length"])
                lines.append("        placeholder_text: %s" % yaml_quote(p["placeholder_text"]))
    if has_tests:
        lines.append("  - name: tests/test_task.py")
        lines.append("    visible: false")
    return "\n".join(lines) + "\n"


def process_task(task_dir, check=False):
    tmpls = sorted(glob.glob(os.path.join(task_dir, "*.tmpl")))
    if not tmpls:
        return None
    file_entries = []
    for tmpl in tmpls:
        with open(tmpl, encoding="utf-8") as fh:
            text = fh.read()
        clean, placeholders = parse_template(text)
        # verify every placeholder slices back to a real span of the clean text
        for p in placeholders:
            span = clean[p["offset"]:p["offset"] + p["length"]]
            if len(span) != p["length"]:
                raise AssertionError("placeholder runs past end of file in %s" % tmpl)
        out_name = os.path.basename(tmpl)[:-len(".tmpl")]
        out_path = os.path.join(task_dir, out_name)
        if not check:
            with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(clean)
        file_entries.append((out_name, placeholders))
        rel = os.path.relpath(out_path, ROOT)
        print("  %s  (%d placeholder%s)" % (rel, len(placeholders), "" if len(placeholders) == 1 else "s"))

    has_tests = os.path.exists(os.path.join(task_dir, "tests", "test_task.py"))
    info = build_task_info(file_entries, has_tests)
    if not check:
        with open(os.path.join(task_dir, "task-info.yaml"), "w", encoding="utf-8", newline="\n") as fh:
            fh.write(info)
    return file_entries


def main(argv):
    ap = argparse.ArgumentParser(description="Build EduTools placeholders from *.tmpl solution templates.")
    ap.add_argument("task_dirs", nargs="*", help="task directories to process")
    ap.add_argument("--all", action="store_true", help="process every *.tmpl under the repo")
    ap.add_argument("--check", action="store_true", help="verify and report; write nothing")
    args = ap.parse_args(argv)

    dirs = list(args.task_dirs)
    if args.all:
        for tmpl in glob.glob(os.path.join(ROOT, "**", "*.tmpl"), recursive=True):
            d = os.path.dirname(tmpl)
            if d not in dirs:
                dirs.append(d)
    if not dirs:
        ap.error("give one or more task directories, or --all")

    total = 0
    for d in dirs:
        d = os.path.abspath(d)
        print("%s:" % os.path.relpath(d, ROOT))
        result = process_task(d, check=args.check)
        if result is None:
            print("  (no *.tmpl found — skipped)")
        else:
            total += 1
    print("\n%s %d task(s)." % ("Checked" if args.check else "Generated placeholders for", total))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
