#!/usr/bin/env python3
"""Scaffold the MiniERP EduTools guided-project skeleton from a curriculum manifest.

This tool is part of the *authoring* toolchain, not the course itself, so it is
written to run on the system Python (3.9+). It reads ``tools/curriculum.json``
(produced from the curriculum-design workflow) and materialises the JetBrains
EduTools folder structure:

    course-info.yaml
    lessonNN-<slug>/
        lesson-info.yaml              (type: framework  -> a guided project / "stages")
        taskNN-<slug>/
            task-info.yaml
            task.md                   (stub description: goals, features, ERP increment)
            task.py                   (starter stub)
            tests/
                __init__.py
                test_task.py          (stub test, skipped until populated)
            __init__.py

It is idempotent: re-running regenerates the generated files. It never deletes
files it did not create (except inside ``--clean`` lesson dirs it manages).

Usage:
    python tools/scaffold_course.py                 # generate from tools/curriculum.json
    python tools/scaffold_course.py --manifest path/to/curriculum.json
    python tools/scaffold_course.py --clean         # remove previously generated lessonNN-* dirs first
    python tools/scaffold_course.py --dry-run       # print what would be created
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_MANIFEST = os.path.join(ROOT, "tools", "curriculum.json")

# Marker so --clean only ever removes lesson dirs this tool generated.
GENERATED_MARKER = ".scaffold-generated"
# Marker a human drops in a lesson dir once it is authored; never regenerated.
POPULATED_MARKER = ".populated"

COURSE_TITLE = "Python by Building MiniERP: From the Basics to Mastery"
COURSE_SUMMARY = (
    "A guided project for working developers learning Python. You build MiniERP, "
    "a small-business ERP suite (inventory, customers, sales & invoicing, payments, "
    "reporting, users & roles, audit log, import/export) with four front-ends "
    "(CLI, Web, desktop GUI, text UI), one stage at a time. The course is "
    "standard-library-first so you understand how Python actually works, then "
    "layers in popular open-source tools. It targets Python 3.14 and aims to leave "
    "no language or standard-library feature unexplored."
)
PY_VERSION = "3.14"


def slugify(value: str) -> str:
    value = (value or "").strip().lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = re.sub(r"-+", "-", value).strip("-")
    return value or "item"


def write(path: str, content: str, dry_run: bool, made: list) -> None:
    if dry_run:
        made.append(path)
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    made.append(path)


def yaml_list(items) -> str:
    return "".join("  - {0}\n".format(i) for i in items)


# --------------------------------------------------------------------------- #
# File templates
# --------------------------------------------------------------------------- #

def course_info_yaml(lesson_dirs) -> str:
    return (
        "# Auto-generated by tools/scaffold_course.py — edit the manifest, not this file.\n"
        "type: marketplace\n"
        "title: \"{title}\"\n"
        "language: English\n"
        "summary: |-\n{summary}\n"
        "programming_language: Python\n"
        "environment: unittest\n"
        "content:\n{content}"
        "yaml_version: 5\n"
    ).format(
        title=COURSE_TITLE,
        summary="".join("  " + line + "\n" for line in COURSE_SUMMARY.splitlines() or [""]),
        content=yaml_list(lesson_dirs),
    )


def lesson_info_yaml(task_dirs, framework=True) -> str:
    # A `framework` lesson is an EduTools guided project: the learner's code
    # propagates from one stage to the next. It must contain ONLY code stages
    # (edu/output) — a theory/choice stage has no code and will not open inside a
    # framework lesson, so those lessons are emitted as regular lessons instead.
    type_line = "type: framework\n" if framework else ""
    return (
        "# Auto-generated by tools/scaffold_course.py\n"
        + type_line
        + "content:\n{content}"
    ).format(content=yaml_list(task_dirs))


def task_info_yaml(task_type: str) -> str:
    header = "# Auto-generated by tools/scaffold_course.py\n"
    if task_type == "choice":
        # A choice task must ship valid options or EduTools loads it "with errors".
        # These are placeholders the author replaces when populating the stage.
        return header + (
            "type: choice\n"
            "is_multiple_choice: false\n"
            "options:\n"
            "  - text: \"TODO(author): the correct answer\"\n"
            "    is_correct: true\n"
            "  - text: \"TODO(author): a distractor\"\n"
            "    is_correct: false\n"
        )
    if task_type == "theory":
        # A theory stage has no code, but it must still declare its description
        # file (task.md). A bare `type: theory` does not render in the IDE; the
        # Welcome lesson's working form declares task.md, so match it.
        return header + (
            "type: theory\n"
            "files:\n"
            "  - name: task.md\n"
            "    visible: true\n"
        )
    if task_type == "output":
        return header + (
            "type: output\n"
            "files:\n"
            "  - name: task.py\n"
            "    visible: true\n"
        )
    # default: edu (auto-checked by unit tests)
    return header + (
        "type: edu\n"
        "files:\n"
        "  - name: task.py\n"
        "    visible: true\n"
        "  - name: tests/test_task.py\n"
        "    visible: false\n"
        "    propagatable: false\n"
        "  - name: __init__.py\n"
        "    visible: false\n"
        "    propagatable: false\n"
        "  - name: tests/__init__.py\n"
        "    visible: false\n"
        "    propagatable: false\n"
    )


def task_md(task: dict, phase_title: str, position: str) -> str:
    feats = ", ".join("`{0}`".format(f.replace("`", "")) for f in task.get("python_features", [])) or "_TBD_"
    goals = "\n".join("- {0}".format(g) for g in task.get("learning_goals", [])) or "- _TBD_"
    return (
        "# {title}\n\n"
        "> **Phase:** {phase}  •  **Stage:** {pos}  •  **Type:** `{ttype}`  •  "
        "**Status:** skeleton (to be populated)\n\n"
        "## What you'll learn\n{goals}\n\n"
        "## Python features introduced\n{feats}\n\n"
        "## MiniERP increment\n{erp}\n\n"
        "---\n\n"
        "<div class=\"hint\" title=\"Author notes (remove when populated)\">\n\n"
        "**TODO(author):** replace this stub with the full task description, then put "
        "starter code in `task.py` and real checks in `tests/test_task.py`.\n\n"
        "- **Starter idea:** {starter}\n"
        "- **Test focus:** {testfocus}\n\n"
        "</div>\n"
    ).format(
        title=task.get("title", "Untitled task"),
        phase=phase_title,
        pos=position,
        ttype=task.get("task_type", "edu"),
        goals=goals,
        feats=feats,
        erp=task.get("erp_increment", "_TBD_"),
        starter=task.get("starter_stub", "_TBD_"),
        testfocus=task.get("test_focus", "_TBD_"),
    )


def task_py(task: dict) -> str:
    return (
        '"""{title}\n\n'
        "MiniERP guided project — stage stub.\n\n"
        "TODO(author): implement this stage.\n"
        "Starter idea: {starter}\n"
        '"""\n\n'
        "# Your code here.\n"
    ).format(
        title=task.get("title", "Untitled task"),
        starter=task.get("starter_stub", "TBD"),
    )


def test_task_py(task: dict) -> str:
    return (
        "import unittest\n\n"
        "# TODO(author): replace with real checks.\n"
        "# Test focus: {focus}\n\n\n"
        "class TestCase(unittest.TestCase):\n"
        '    @unittest.skip("skeleton: this task has not been populated yet")\n'
        "    def test_placeholder(self):\n"
        '        self.fail("populate this task")\n'
    ).format(focus=task.get("test_focus", "TBD"))


# --------------------------------------------------------------------------- #
# Curriculum.md (human-readable blueprint)
# --------------------------------------------------------------------------- #

def build_curriculum_md(data: dict, lessons_flat) -> str:
    out = []
    out.append("# MiniERP — Curriculum Blueprint\n")
    out.append(
        "Auto-generated from `tools/curriculum.json` by `tools/scaffold_course.py`. "
        "This is the master map of the guided project: every phase (an EduTools "
        "*framework lesson* / guided project), its lessons, and every stage/task with "
        "the Python features it teaches and the MiniERP increment it delivers.\n"
    )
    totals = data.get("totals", {})
    out.append(
        "- **Capstone:** {cap}\n- **Python:** {ver}\n- **Phases:** {p}  •  "
        "**Lessons:** {l}  •  **Tasks/stages:** {t}\n- **Dependency policy:** "
        "standard-library-first, then free/open-source libraries — no paid services.\n".format(
            cap=data.get("capstone", "MiniERP"),
            ver=data.get("python_version", PY_VERSION),
            p=totals.get("phases", "?"),
            l=totals.get("lessons", "?"),
            t=totals.get("tasks", "?"),
        )
    )
    out.append(
        "\nBefore populating any stage, read `docs/AUTHORING_NOTES.md` "
        "(continuity rules and the per-stage populate checklist).\n"
    )
    out.append("\n---\n")

    for (lesson_dir, phase, lesson) in lessons_flat:
        out.append("\n## {ldir} — {title}\n".format(ldir=lesson_dir, title=lesson.get("title", "")))
        out.append("*Phase: {0} — milestone: {1}*\n".format(
            phase.get("phase_title", ""), phase.get("erp_milestone", "")))
        if lesson.get("summary"):
            out.append("\n" + lesson["summary"].strip() + "\n")
        out.append("\n| # | Task | Type | Python features | MiniERP increment |\n")
        out.append("|---|------|------|-----------------|-------------------|\n")
        for i, task in enumerate(lesson.get("tasks", []), start=1):
            feats = ", ".join(task.get("python_features", []))
            feats = feats.replace("`", "").replace("|", "\\|")
            erp = task.get("erp_increment", "").replace("|", "\\|").replace("\n", " ")
            out.append("| {n} | {title} | {ttype} | {feats} | {erp} |\n".format(
                n=i,
                title=task.get("title", "").replace("|", "\\|"),
                ttype=task.get("task_type", "edu"),
                feats=feats,
                erp=erp,
            ))
    out.append("\n")
    return "".join(out)


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #

def clean_generated(dry_run: bool) -> int:
    removed = 0
    for name in sorted(os.listdir(ROOT)):
        path = os.path.join(ROOT, name)
        if os.path.isdir(path) and re.match(r"lesson\d{2}-", name):
            if os.path.exists(os.path.join(path, POPULATED_MARKER)):
                print("  keep {0} (.populated — authored by hand)".format(name))
                continue
            if os.path.exists(os.path.join(path, GENERATED_MARKER)) or dry_run:
                print("  remove {0}".format(name))
                if not dry_run:
                    shutil.rmtree(path)
                removed += 1
    return removed


def main(argv) -> int:
    ap = argparse.ArgumentParser(description="Scaffold the MiniERP EduTools skeleton.")
    ap.add_argument("--manifest", default=DEFAULT_MANIFEST)
    ap.add_argument("--clean", action="store_true", help="remove previously generated lessonNN-* dirs first")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args(argv)

    if not os.path.exists(args.manifest):
        print("Manifest not found: {0}".format(args.manifest), file=sys.stderr)
        print("Run the curriculum-design workflow first, then write its output to that path.", file=sys.stderr)
        return 2

    with open(args.manifest, encoding="utf-8") as fh:
        data = json.load(fh)

    manifest = data.get("manifest", [])
    if not manifest:
        print("Manifest has no 'manifest' phases array.", file=sys.stderr)
        return 2

    if args.clean:
        print("Cleaning generated lesson dirs:")
        clean_generated(args.dry_run)

    made = []
    lesson_dirs = []
    lessons_flat = []  # (lesson_dir, phase, lesson)
    lesson_no = 0

    for phase in manifest:
        phase_title = phase.get("phase_title", "")
        for lesson in phase.get("lessons", []):
            lesson_no += 1
            ldir_name = "lesson{0:02d}-{1}".format(lesson_no, slugify(lesson.get("slug", lesson.get("title", "lesson"))))
            ldir = os.path.join(ROOT, ldir_name)
            lesson_dirs.append(ldir_name)
            lessons_flat.append((ldir_name, phase, lesson))

            # Never overwrite a hand-authored lesson; still list it in the course.
            if os.path.exists(os.path.join(ldir, POPULATED_MARKER)):
                print("  skip {0} (.populated — authored by hand)".format(ldir_name))
                continue

            task_dirs = []
            tasks = lesson.get("tasks", [])
            for t_no, task in enumerate(tasks, start=1):
                tdir_name = "task{0:02d}-{1}".format(t_no, slugify(task.get("slug", task.get("title", "task"))))
                task_dirs.append(tdir_name)
                tdir = os.path.join(ldir, tdir_name)
                ttype = task.get("task_type", "edu")
                position = "{0}.{1} of {2}".format(lesson_no, t_no, len(tasks))

                # Only edu tasks are Python packages (their tests import the module);
                # theory/choice stages carry no code, so no stray __init__.py.
                if ttype == "edu":
                    write(os.path.join(tdir, "__init__.py"), "", args.dry_run, made)
                write(os.path.join(tdir, "task-info.yaml"), task_info_yaml(ttype), args.dry_run, made)
                write(os.path.join(tdir, "task.md"), task_md(task, phase_title, position), args.dry_run, made)
                if ttype not in ("choice", "theory"):
                    write(os.path.join(tdir, "task.py"), task_py(task), args.dry_run, made)
                if ttype == "edu":
                    write(os.path.join(tdir, "tests", "__init__.py"), "", args.dry_run, made)
                    write(os.path.join(tdir, "tests", "test_task.py"), test_task_py(task), args.dry_run, made)

            non_code = any(t.get("task_type", "edu") in ("theory", "choice") for t in tasks)
            write(os.path.join(ldir, "lesson-info.yaml"),
                  lesson_info_yaml(task_dirs, framework=not non_code), args.dry_run, made)
            write(os.path.join(ldir, GENERATED_MARKER), "generated by tools/scaffold_course.py\n", args.dry_run, made)

    # course-level files
    # The hand-authored "Welcome" lesson (a plain lesson with a single theory
    # "Start here" task) is the course landing page. It is not generated from the
    # manifest; we just list it first in course-info.yaml when its dir exists.
    welcome_dir = os.path.join(ROOT, "Welcome")
    top_items = (["Welcome"] if os.path.isdir(welcome_dir) else []) + lesson_dirs
    write(os.path.join(ROOT, "course-info.yaml"), course_info_yaml(top_items), args.dry_run, made)
    write(os.path.join(ROOT, "CURRICULUM.md"), build_curriculum_md(data, lessons_flat), args.dry_run, made)

    print("\n{0} {1} files across {2} lessons.".format(
        "Would create" if args.dry_run else "Created/updated", len(made), len(lesson_dirs)))
    print("Course: {0}".format(COURSE_TITLE))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
